version: 2.1
orbs:
    docker: circleci/docker@2.1.2
jobs:
  build-devcontainer:
    executor: docker/docker
    environment:
      IMAGE_NAME: csu-booking-platform/devcontainer
      DOCKER_REGISTRY: ghcr.io
    steps:
        - setup_remote_docker:
            version: 20.10.11
        - checkout
        - run:
            name: Build docker image
            command: |
              cd devcontainer
              docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}-${CIRCLE_SHA1} .
  build-and-release-devcontainer:
    executor: docker/docker
    environment:
      IMAGE_NAME: csu-booking-platform/devcontainer
      DOCKER_REGISTRY: ghcr.io
      GITHUB_OWNER: csu-booking-platform
      GITHUB_REPO: container-spec
    steps:
        - setup_remote_docker:
            version: 20.10.11
        - add_ssh_keys:
            fingerprints:
              -  "74:6a:ad:46:d3:93:e1:39:c2:56:6b:0c:61:06:a4:24"
        - checkout
        - run:
            name: Get next version
            command: |
              curl -L https://github.com/idc101/git-mkver/releases/download/v1.1.1/git-mkver-linux-amd64-1.1.1.tar.gz | tar xvz
              sudo mv git-mkver /usr/local/bin
              git mkver next
              if [ $(git tag -l "$(git mkver next)") ]; then
                circleci-agent step halt
              else
                echo "export TAG=$(git mkver next)" >> $BASH_ENV
              fi
        - run:
            name: Build docker image
            command: |
              cd devcontainer
              docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG} .
        - run:
            name: Publish docker image
            command: |
              docker login $DOCKER_REGISTRY -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
              docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}
        - run:
            name: Create Release
            command: |
              wget https://github.com/github-release/github-release/releases/download/v0.8.1/linux-amd64-github-release.bz2
              bzip2 -d linux-amd64-github-release.bz2
              chmod +x linux-amd64-github-release
              mv linux-amd64-github-release ghr
              git mkver tag
              git push --tags
              ./ghr release \
                --tag $TAG \
                --security-token $DOCKER_PASSWORD \
                --user $GITHUB_OWNER \
                --repo $GITHUB_REPO


workflows:
  build:
    jobs:
      - build-devcontainer:
          filters:  # using regex filters requires the entire branch to match
            branches:
              ignore:  # only branches matching the below regex filters will run
                - main
      - build-and-release-devcontainer:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - main
